"""journal_and_birth_chart

Revision ID: 8a353838638a
Revises: 185a30706ca1
Create Date: 2026-05-13 10:53:42.070117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a353838638a'
down_revision: Union[str, Sequence[str], None] = '185a30706ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_journal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('is_reversed', sa.Boolean(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_journal_date'), 'daily_journal', ['date'], unique=False)
    op.create_index(op.f('ix_daily_journal_user_id'), 'daily_journal', ['user_id'], unique=False)
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('birth_time', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('birth_place', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('birth_lat', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('birth_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth_lng')
    op.drop_column('users', 'birth_lat')
    op.drop_column('users', 'birth_place')
    op.drop_column('users', 'birth_time')
    op.drop_column('users', 'birth_date')
    op.drop_index(op.f('ix_daily_journal_user_id'), table_name='daily_journal')
    op.drop_index(op.f('ix_daily_journal_date'), table_name='daily_journal')
    op.drop_table('daily_journal')
    # ### end Alembic commands ###
